name: courseplease
description: CoursePlease.com client app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  #sdk: ">=2.12.0-133.2.beta <3.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bubble: ^1.2.1
  cached_network_image: ^3.0.0-nullsafety       # Unstable
  charcode: ^1.2.0
  device_info: ^2.0.0
  easy_localization: ^3.0.0
  flag: ^5.0.0-nullsafety                       # Unstable
  flutter_breadcrumb: ^1.0.1
  flutter_icons: ^1.1.0                         # No null-safety
  flutter_markdown: ^0.6.0
  flutter_secure_storage: ^4.1.0
  flutter_svg: ^0.21.0-nullsafety.0             # Unstable
  flutter_webview_plugin: ^0.3.11               # No null-safety
  flutter_tags: ^1.0.0-nullsafety.1             # Unstable
  flutter_treeview: ^0.8.0+1                    # No null-safety
  get_it: ^6.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0                          # No null-safety
  http: ^0.13.0
  intl: ^0.17.0
  meta: ^1.3.0
  package_info: ^2.0.0
  provider: ^5.0.0
  rxdart: ^0.26.0
  uuid: ^3.0.2
  visibility_detector: ^0.2.0-nullsafety.1      # Unstable
  yaml: ^3.1.0
  #youtube_player_flutter: ^7.0.0+7
  #youtube_player_iframe: ^1.2.0+2               # No null-safety
  youtube_plyr_iframe: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
# This is commented out because it is incompatible with null-safety packages.
# And we have no tests so far anyway.
#  integration_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/auth_providers/facebook.svg
    - assets/auth_providers/google.svg
    - assets/auth_providers/instagram.svg
    - assets/auth_providers/vk.svg
    - assets/translations/en.yaml
    - assets/translations/ru.yaml

  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
