name: courseplease
description: CoursePlease.com client app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  # Our own packages:
#  model_interfaces:
#    path: '../../../dart/model_interfaces'
  model_interfaces: ^0.1.0

#  model_editors:
#    path: '../../../dart/model_editors'
  model_editors: ^0.1.2

  # SDK packages:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Third-party packages.
  ably_flutter: ^1.2.1                          # No web
  # bubble: ^1.2.1                                # No web: https://github.com/vi-k/bubble/issues/38
  cached_network_image: ^3.1.0                  # Indicates no web but works
  charcode: ^1.3.1
  clipboard: ^0.1.3
  collection: ^1.15.0
  device_info: ^2.0.2                           # No web, MIGRATE TO device_info_plus
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  flag: ^5.0.1                                  # Indicates no web but works
  flutter_facebook_auth: ^3.5.0+1
  flutter_markdown: ^0.6.6
  flutter_rating_bar: ^4.0.0
  flutter_secure_storage: ^5.0.0-beta.5                # No web, Beta supports web
  flutter_svg: ^0.22.0                          # Indicates no web but works with CanvasKit. See https://github.com/dnfield/flutter_svg/issues/540 for HTML
  flutter_webview_plugin: ^0.4.0                # No web
  flutter_treeview: ^1.0.6+1
  flutter_typeahead: ^3.2.1
  get_it: ^7.2.0
  google_maps_flutter: ^2.0.6                   # No web
  google_sign_in: ^5.0.7
  hive: ^2.0.4
  hive_flutter: ^1.0.0                          # No null-safety
  http: ^0.13.3
  image: ^3.0.4
  image_picker: ^0.8.4
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.5955-rc.1 # Unstable
  package_info_plus: ^1.0.6
  pointycastle: ^3.3.4
  provider: ^6.0.0                              # TODO: Remove
  rxdart: ^0.27.2

  # TODO: Use pub when this is done: https://github.com/jamiewest/sse_client/issues/8
  sse_client:
    git:
      url: https://github.com/alexeyinkin/sse_client.git
      ref: issue8_connection-management

  url_strategy: ^0.2.0
  uuid: ^3.0.4
  visibility_detector: ^0.2.0
  xml: ^5.3.0
  #webview_flutter: ^2.0.10                      # TODO: Test 2.0.13, Migrate to this when it supports Tinkoff payment page.
  yaml: ^3.1.0
  #youtube_player_flutter: ^7.0.0+7
  #youtube_player_iframe: ^1.2.0+2               # No null-safety
  youtube_plyr_iframe: ^2.0.7                     # // https://github.com/sarbagyastha/youtube_player_flutter/issues/460#issuecomment-799992113

dev_dependencies:
  flutter_test:
    sdk: flutter
# This is commented out because it is incompatible with null-safety packages.
# And we have no tests so far anyway.
#  integration_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/auth_providers/facebook.svg
    - assets/auth_providers/google.svg
    - assets/auth_providers/instagram.svg
    - assets/auth_providers/vk.svg

    - assets/translations/en.yaml
    - assets/translations/ru.yaml

    - assets/flags/arabic.svg
    - assets/flags/by.svg

    - assets/currency_rates/cbr_daily.xml

  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
